Apr 07 13:37:08.31
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:37:12,380 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:37:12,380 - utils - INFO - Python: 3.12.8 2025-04-07 11:37:12,391 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:24.35
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:27,788 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:27,788 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:27,806 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:24.31
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:27,833 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:27,833 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:27,848 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:22.42
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:25,760 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:25,760 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:25,771 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:21.03
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:24,401 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:24,401 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:24,411 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:20.83
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:24,278 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:24,278 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:24,294 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:18.61
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:21,962 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:21,963 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:21,981 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:18.21
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:21,908 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:21,908 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:21,926 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:16.50
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:20,009 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:20,009 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:20,027 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:15.19
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:18,699 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:18,699 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:18,708 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:12.51
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:14,904 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:14,905 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:14,918 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue. 2025-04-07 11:34:18,445 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:18,446 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:18,464 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:11.93
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:15,169 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:15,169 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:15,186 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:11.06
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:13,403 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:13,403 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:13,416 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue. 2025-04-07 11:34:16,866 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:16,866 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:16,883 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:11.04
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:13,513 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:13,513 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:13,525 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue. 2025-04-07 11:34:17,152 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:17,152 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:17,171 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:09.47
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:12,065 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:12,065 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:12,077 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue. 2025-04-07 11:34:15,794 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:15,794 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:15,813 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:09.39
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:11,754 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:11,754 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:11,766 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue. 2025-04-07 11:34:15,189 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:15,189 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:15,207 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:07.88
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:10,362 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:10,362 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:10,377 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue. 2025-04-07 11:34:13,821 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:13,821 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:13,831 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
Apr 07 13:34:07.71
GET
500
clipbaord-dhjwxy4n0-kagabolucky72-gmailcoms-projects.vercel.app
/
2025-04-07 11:34:11,160 - utils - INFO - Running on Vercel serverless environment 2025-04-07 11:34:11,160 - utils - INFO - Python: 3.12.8 2025-04-07 11:34:11,169 - database - ERROR - Error initializing database: Can't load plugin: sqlalchemy.dialects:postgres Traceback (most recent call last): File "/var/task/vc__handler__python.py", line 14, in <module> __vc_spec.loader.exec_module(__vc_module) File "<frozen importlib._bootstrap_external>", line 999, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/var/task/api/index.py", line 13, in <module> from web_app import app File "/var/task/web_app.py", line 33, in <module> db_manager = DatabaseManager() ^^^^^^^^^^^^^^^^^ File "/var/task/database.py", line 50, in __init__ self.engine = create_engine(db_url) ^^^^^^^^^^^^^^^^^^^^^ File "<string>", line 2, in create_engine File "/var/task/sqlalchemy/util/deprecations.py", line 281, in warned return fn(*args, **kwargs) # type: ignore[no-any-return] ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/create.py", line 553, in create_engine entrypoint = u._get_entrypoint() ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/engine/url.py", line 772, in _get_entrypoint cls = registry.load(name) ^^^^^^^^^^^^^^^^^^^ File "/var/task/sqlalchemy/util/langhelpers.py", line 375, in load raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres Python process exited with exit status: 1. The logs above can help with debugging the issue.
No more logs to show within selected timeline